### ISSUE TITLE
Details about ImageNet experiments setting

### ISSUE THREAD

**Issue by licj15** [htqin/IR-Net#6]
@htqin Thank you for your quick response! I intended to ask this in this [issue](https://github.com/htqin/IR-Net/issues/5), but it was closed and this seems to be a new question, so I open a new issue for this question. Thank you a lot!

I notice in the yaml

```
    augmentation:
        input_size: 224
        test_resize: 256
        colorjitter: [0.2, 0.2, 0.2, 0.1] 
```
1. Does it mean you use 224224 for train, and upsample it to 256256 during test? If so, I noticed you didn't mention so in your paper, do you have any references for this? I was wondering if such techniques are also used in baselines.
2. Do you only use "colorjitter: [0.2, 0.2, 0.2, 0.1]" for augmentation? Do you use random crop or flip? Because I noticed you use such augmentation in CIFAR-10, not sure if you use any other augmentation beside "colorjitter: [0.2, 0.2, 0.2, 0.1]" for ImageNet.

Thank you! Your efforts and the sprit to open source will benefit the community a lot!
